version: '3.3'
services:
  mongodb:
    image : mongo
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - nesjs-network
    restart: always
  reservations:
    image: kushalgaur123/reservations:latest
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
    command: pnpm run start:prod
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  auth:
    image: kushalgaur123/auth:latest
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    command: pnpm run start:prod
    env_file:
      - .env
    ports:
      - 3001:3001
      - 3003:3003
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  hotels:
    image: kushalgaur123/hotels:latest
    build:
      context: .
      dockerfile: ./apps/hotels/Dockerfile
    command: pnpm run start:prod
    env_file:
      - .env
    ports:
      - 3002:3002
      - 3004:3004
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  gateway:
    image: kushalgaur123/gateway:latest
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    command: pnpm run start:prod
    env_file:
      - .env
    ports:
      - 3005:3005
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
networks:
    nesjs-network:
      driver: bridge
